-- Ngày thay đổi	: {CURRENT_TIME}
-- Người thay đổi	:
-- Phiên bản 		  :
-- Mô tả			    : Stream sink/transform dữ liệu init trước khi đẩy xuống DW

CREATE OR REPLACE STREAM DW_{TABLE_NAME}_INIT WITH(KAFKA_TOPIC='DW_{TABLE_NAME}_INIT',PARTITIONS=1) AS SELECT
  DATA.ROWKEY ROWKEY,
  DATA.LOOKUP_KEY LOOKUP_KEY,
  DATA.RECID RECID,
  -- Để ý xem có phải bảng his hay không nếu có thêm trường recver (Note cho BNH: Sửa xong thì xoá) --
  DATA.OP_TS OP_TS,
  DATA.REP_TS REP_TS,
  TIMESTAMPTOSTRING(UNIX_TIMESTAMP(), 'yyyy-MM-dd HH:mm:ss.SSSSSS') CURRENT_TS,
  PARSE_TIMESTAMP(DATA.OP_TS, 'yyyy-MM-dd HH:mm:ss.SSSSSS') COMMIT_TS,
  PARSE_TIMESTAMP(DATA.REP_TS, 'yyyy-MM-dd HH:mm:ss.SSSSSS') REPLICAT_TS,
  PARSE_TIMESTAMP(TIMESTAMPTOSTRING(UNIX_TIMESTAMP(), 'yyyy-MM-dd HH:mm:ss.SSSSSS'), 'yyyy-MM-dd HH:mm:ss.SSSSSS') STREAM_TS,
  DATA.TABLE_NAME TABLE_NAME,
  CAST(DATA.COMMIT_SCN AS BIGINT) COMMIT_SCN,
  DATA.COMMIT_ACTION COMMIT_ACTION,
--{FIELD_NAMES},
  CAST(NVL(DATA.XMLRECORD['IDX'], '1') AS INTEGER) V_M,
  CAST(NVL(DATA.XMLRECORD['IDX_S'], '1') AS INTEGER) V_S,
  (CASE WHEN ((DATA.XMLRECORD['RECID'] = (DATA.RECID + '_TOMBSTONE')) OR (DATA.COMMIT_ACTION = 'D')) THEN 'DELETE' ELSE 'LIVE' END) FLAG_STATUS,
	DATA.BANKING_DATE BANKING_DATE
FROM FBNK_{TABLE_NAME}_INIT_MULTIVALUE DATA
EMIT CHANGES;